### ISSUE TITLE
Long-lived short variable names makes the reading experience suboptimal

### ISSUE THREAD

**Issue by gaborszakacs** [azorahai3724/codecoverage-thesis#4]
It's idiomatic to use short, even one letter variable names, but only if they live for very few lines. Having to keep in mind all the different variable names in long functions is hard for the reader, e.g. in `newApp()`

Consider using more meaningful names, and consider refactoring long methods to smaller well-named ones.

**Comment by gaborszakacs** [comment]
Similar here, I have no idea what's happening here on first glance, I have to dig deeper and look at the string operations/etc, the variable names should help me understand :)

```
l := s[strings.LastIndex(s, ")")+1:]

		ts := strings.Split(l, "%")

		ps := strings.TrimSpace(ts[0])

		pf, err := strconv.ParseFloat(ps, 64)
		if err != nil {
			log.Fatalf("parsing coverage file: %s", err)
		}
		return pf, nil
```

**Comment by azorahai3724** [comment]
I totally agree with this, I just was lazy to give proper names and wanted to get the functionality up and running fast
